# -*- coding: utf-8 -*-
"""RM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eh9YSlTk-OxtwjLD1KMSXtdjBYdTZt3P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

filename = 'GDP_and_Major_Industrial_Sectors_of_Economy_Dataset.xls' #'data.csv'
data =  pd.read_excel(filename)
data.dropna(inplace=True)
columns = list(data.head(0))
dps = data.to_numpy()
print(dps.shape,dps)

# Scatter Plot
plt.figure(figsize=(8,8))
plt.scatter(dps[:,14], dps[:,16],s=20)
plt.title('GDP Growth Rate(%) vs Agri Growth Rate(%)',fontsize=15)
plt.xlabel(columns[14],fontsize=15)
plt.ylabel(columns[16],fontsize=15)
plt.grid()
plt.savefig('Scatter.png')
plt.show()

# Box Plot
cols = []
for ele in columns[14:]:
  cols.append(ele.split('%')[0][:-2])
plt.figure(figsize=(8,8))
plt.boxplot(dps[:,14:],vert = 0)
plt.title('Growth Rate (%) in Various Sectors',fontsize=15)
plt.yticks(np.arange(1,8),cols,rotation=0,fontsize=15)
plt.xlabel('Growth Rate (%)',fontsize=15)
plt.savefig('BoxPlot.png')
plt.show()

# Bar Plot
plt.figure(figsize=(14,14))
ind = np.arange(0,6)
width = 0.35

plt.bar(ind,dps[:6,2],width,color='r')
plt.bar(ind,dps[:6,3],width,color='b')
plt.bar(ind,dps[:6,4],width,color='g')
plt.grid()
plt.ylabel('Prices in Rs Cr',fontsize=15)
plt.xticks(ind,dps[:6,0],rotation=45,fontsize=15)
plt.legend(labels=columns[2:5],fontsize=12)
plt.savefig('BarPlot.png')
plt.show()